// Generated by scripts/build-search-vectors.mjs. Do not edit.
// Not built yet (see semantic-data.ts): /api/search answers 503 until it is.
export const VEC_SLUGS: string[] = [];
export const VEC_SCALE = 1;
export const VEC_DATA = "";
