// Generated by scripts/build-search-vectors.mjs. Do not edit.
// Not built yet: the Gemini free tier allows 1,000 embeddings a day; until the build
// has run, search uses its lexical engine and exercise-feature vectors only.
export const SEM_SLUGS: string[] = [];
export const SEM_TERMS: string[] = [];
export const SEM_TOP_K = 24;
export const SEM_RANGE: [number, number] = [0, 1];
export const SEM_DATA = "";
