import { Component, isValidElement, useEffect, useMemo, useState, type ReactElement, type ReactNode } from "react";
import { createRoot } from "react-dom/client";
import RootLayout from "@/app/layout";
// Generated by scripts/build-artifact.mjs from the pages under src/app.
import { ROUTES, NotFoundPage } from "artifact-routes";
import { useLocation } from "./router";
import { NotFoundError } from "./shims/next-navigation";

type PageModule = { default: (props: { params: Promise<Record<string, string>>; searchParams: Promise<Record<string, string>> }) => unknown };

function match(pathname: string): { mod: PageModule; params: Record<string, string> } | null {
  const parts = pathname.split("/").filter(Boolean);
  for (const route of ROUTES as { pattern: string; mod: PageModule }[]) {
    const segs = route.pattern.split("/").filter(Boolean);
    if (segs.length !== parts.length) continue;
    const params: Record<string, string> = {};
    const ok = segs.every((s, i) => {
      if (s.startsWith("[") && s.endsWith("]")) {
        params[s.slice(1, -1)] = decodeURIComponent(parts[i]);
        return true;
      }
      return s === parts[i];
    });
    if (ok) return { mod: route.mod, params };
  }
  return null;
}

function Missing() {
  return NotFoundPage ? <NotFoundPage /> : <p style={{ padding: 32, textAlign: "center" }}>Page not found.</p>;
}

/** Renders the matched page. Async (server) pages are awaited first; client pages render as elements. */
function RouteView() {
  const { pathname, search } = useLocation();
  const key = pathname + search;
  const found = useMemo(() => match(pathname), [pathname]);
  const props = useMemo(
    () => ({
      params: Promise.resolve(found?.params ?? {}),
      searchParams: Promise.resolve(Object.fromEntries(new URLSearchParams(search))),
    }),
    [found, search],
  );
  const Page = found?.mod.default;
  const isAsync = Page?.constructor.name === "AsyncFunction";
  const [loaded, setLoaded] = useState<{ key: string; node: ReactNode } | null>(null);

  useEffect(() => {
    if (!Page || !isAsync) return;
    let cancelled = false;
    Promise.resolve()
      .then(() => Page(props))
      .then((node) => !cancelled && setLoaded({ key, node: node as ReactNode }))
      .catch((err) => {
        if (cancelled) return;
        if (!(err instanceof NotFoundError)) console.error(err);
        setLoaded({ key, node: <Missing /> });
      });
    return () => {
      cancelled = true;
    };
  }, [Page, isAsync, props, key]);

  let node: ReactNode;
  if (!Page) node = <Missing />;
  else if (!isAsync) {
    const Client = Page as unknown as (p: typeof props) => ReactNode;
    node = <Client {...props} />;
  } else if (loaded?.key === key) node = loaded.node;
  else return <div style={{ minHeight: "60vh" }} />;
  return <Boundary key={key}>{node}</Boundary>;
}

class Boundary extends Component<{ children: ReactNode }, { failed: boolean }> {
  state = { failed: false };
  static getDerivedStateFromError(err: unknown) {
    if (!(err instanceof NotFoundError)) console.error(err);
    return { failed: true };
  }
  render() {
    return this.state.failed ? <Missing /> : this.props.children;
  }
}

/** Reuses the app's real layout: renders the children of its <body> inside a div. */
function Shell() {
  const html = RootLayout({ children: <RouteView /> } as never) as ReactElement<{ children: ReactNode }>;
  const body = isValidElement(html) ? (html.props.children as ReactElement<{ className?: string; children: ReactNode }>) : null;
  if (!body || !isValidElement(body)) return <RouteView />;
  return <div className={body.props.className}>{body.props.children}</div>;
}

createRoot(document.getElementById("root")!).render(<Shell />);
